# This is the GitHub Action which
# automatically updates https://www.fineract.dev
#
# see https://jira.apache.org/jira/browse/FINERACT-970
# https://github.com/marketplace/actions/setup-gcloud-environment
# and http://blog2.vorburger.ch/2020/05/fineractdev-cicd-from-github-to-google.html
#
# Created by Michael Vorburger.ch for Fineract in May 2020.
#

name: Deploy to Gedit GCP Instance

on:
  push:
    branches:
      - gedit-1.6.0

jobs:
  setup-build-deploy:
    name: Deploy on Gedit GCP
    if: github.repository == 'openMF/fineract'
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - id: 'auth'
        uses: google-github-actions/auth@v0
        with:
          credentials_json: '${{ secrets.GOOGLE_APPLICATION_CREDENTIALS_GEDIT}}'

      - uses: google-github-actions/setup-gcloud@v0
        with:
          project_id: ${{ secrets.GOOGLE_PROJECT_ID_GEDIT }}

      - name: Pull from Docker Hub
        run: |
            docker pull fintecheando/fineract:1.6.1

      - name: Tag the Image for GCR.io Docker Repository
        run: |
            docker tag fintecheando/fineract:1.6.1 gcr.io/${{ secrets.GOOGLE_PROJECT_ID_GEDIT }}/fintecheando/fineract:1.6.1

      - name: Push the Image for GCR.io Docker Repository
        run: |
            docker push gcr.io/${{ secrets.GOOGLE_PROJECT_ID_GEDIT }}/fintecheando/fineract:1.6.1

      - name: Deploy to Cloud Run  
        run: |
            gcloud run deploy --image=gcr.io/${{ secrets.GOOGLE_PROJECT_ID_GEDIT }}/fintecheando/fineract:1.6.1 \
              --port=8443 --region=us-central1 --allow-unauthenticated --platform=managed 