# This is the GitHub Action which
# automatically updates https://www.fineract.dev
#
# see https://jira.apache.org/jira/browse/FINERACT-970
# https://github.com/marketplace/actions/setup-gcloud-environment
# and http://blog2.vorburger.ch/2020/05/fineractdev-cicd-from-github-to-google.html
#
# Created by Michael Vorburger.ch for Fineract in May 2020.
#

name: Deploy to Gedit GCP Instance

on:
  push:
    branches:
      - gedit-1.6.0

jobs:
  setup-build-deploy:
    name: Deploy on Gedit GCP
    if: github.repository == 'openMF/fineract'
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - id: 'auth'
        uses: google-github-actions/auth@v0
        with:
          credentials_json: '${{ secrets.GOOGLE_APPLICATION_CREDENTIALS_GEDIT}}'

      - uses: google-github-actions/setup-gcloud@v0
        with:
          project_id: ${{ secrets.GOOGLE_PROJECT_ID_GEDIT }}

      - run: gcloud components install beta

      - run: JOBS=$(gcloud beta builds list --ongoing --format="value[terminator=' '](id)") && [ ! -z "$JOBS" ] && echo "Cancelling $JOBS..." && gcloud builds cancel $JOBS --no-user-output-enabled || true

      - run: gcloud beta builds triggers list

      - run: gcloud beta builds triggers run deploy-demo --branch=gedit-1.6.0
